import Indicator from "@/components/Indicator";
import TopMenu from "@/components/TopMenu";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = localFont({
  src: "../../public/fonts/Inter.var.woff2",
  variable: "--font-sans",
});

const fontMono = localFont({
  src: "../../public/fonts/SpaceMono-Regular.woff2",
  variable: "--font-mono",
});

const fontTitle = localFont({
  src: "../../public/fonts/Doctor.woff2",
  variable: "--font-title",
});

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable,
          fontTitle.variable
        )}
      >
        <TopMenu />
        {children}
        <Indicator />
      </body>
    </html>
  );
}
