import Indicator from "@/components/Indicator";
import NextAuthProvider from "@/components/NextAuthProvider";
import ThemeRegistry from "@/components/ThemeRegistry";
import TopMenu from "@/components/TopMenu";
import { fontMono, fontSans, fontTitle } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontMono.variable,
          fontTitle.variable
        )}
      >
        <ReduxProvider>
          <NextAuthProvider session={session}>
            <ThemeRegistry>
              <TopMenu />
              {children}
              <Indicator />
            </ThemeRegistry>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
