import Indicator from "@/components/Indicator";
import ThemeRegistry from "@/components/ThemeRegistry";
import TopMenu from "@/components/TopMenu";
import { fontMono, fontSans, fontTitle } from "@/lib/fonts";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col bg-background pt-20 font-sans antialiased",
          fontSans.variable,
          fontMono.variable,
          fontTitle.variable
        )}
      >
        <ThemeRegistry>
          <TopMenu />
          {children}
          <Indicator />
        </ThemeRegistry>
      </body>
    </html>
  );
}
